export const SUBAREA_LABELS: Record<string, string> = {
  corto_plazo: 'plan de negocio y metas',
  mediano_plazo: 'plan de crecimiento',
  largo_plazo: 'contingencia y resiliencia',
  analisis_ambiental: 'análisis del entorno',
  margen_rentabilidad: 'costeo y rentabilidad',
  control_financiero: 'control financiero',
  planificacion_fin: 'planificación financiera',
  indicadores_fin: 'indicadores financieros',
  planificacion_mkt: 'captación de clientes',
  relacion_clientes: 'relación con clientes',
  medios_online: 'marketing digital',
  logistica: 'logística y recursos',
  procesos: 'procesos operativos',
  calidad: 'calidad y entrega',
  reclutamiento: 'proceso de contratación',
  entrenamiento: 'capacitación del equipo',
  retencion: 'retención y bienestar',
  cumplimiento_laboral: 'cumplimiento laboral',
  personas: 'gestión de personas',
};
